feat: add subscriptions
MishaSmr/java-explore-with-me pull request #2
Opened 2022-09-29 16:31 UTC by MishaSmr

Добавлена функциональность - подписки
Возможность подписываться на других пользователей и получать список актуальных событий, опубликованных этими пользователями.
Возможность получать список актуальных событий, в которых пользователи, на которых осуществлена подписка, принимают участие, при условии, что они одобрили просмотр таких событий

2022-09-29 19:42 UTC, sniskorodnova commented on ewm-service/src/main/resources/schema.sql
> +    CONSTRAINT pk_user_follower PRIMARY KEY (user_id, follower_id),
вот тут не очень понятно зачем такой констрейнт, ведь первичный ключ здесь id. либо можно поле id вообще убрать и сделать первичный ключ (user_id, follower_id)

2022-09-29 19:43 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/explorewithme/subscription/dto/SubscriptionDto.java
> +    Long id;
поле лучше сделать private

2022-09-29 19:50 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/explorewithme/subscription/SubscriptionMapper.java
> +public class SubscriptionMapper {
(необязательно) Можно добавить аннотацию @NoArgsConstructor(access = AccessLevel.PRIVATE), чтобы запретить создавать объекты данного класса, так как у него все методы статичны

2022-09-29 20:03 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/explorewithme/subscription/SubscriptionServiceImpl.java
> +    public List<EventShortDto> getEvents(Long followerId, String type, Integer from, Integer size) {
как предложение - тут наверное можно сделать так, чтобы и прошедшие события подписчики тоже видели, будет история посещений событий:)

2022-09-29 20:03 UTC, sniskorodnova reviewed
есть пара небольших замечаний, в целом всё логично и хорошо сделано

2022-09-30 14:38 UTC, MishaSmr commented on ewm-service/src/main/resources/schema.sql
> +    CONSTRAINT pk_user_follower PRIMARY KEY (user_id, follower_id),
id пока решил оставить, а сочетание user_id-follower_id сделал уникальным

2022-09-30 14:38 UTC, MishaSmr commented on ewm-service/src/main/java/ru/practicum/explorewithme/subscription/dto/SubscriptionDto.java
> +    Long id;
Поправил

2022-09-30 14:38 UTC, MishaSmr commented on ewm-service/src/main/java/ru/practicum/explorewithme/subscription/SubscriptionMapper.java
> +public class SubscriptionMapper {
Спасибо, буду пользоваться)

2022-09-30 14:38 UTC, MishaSmr commented on ewm-service/src/main/java/ru/practicum/explorewithme/subscription/SubscriptionServiceImpl.java
> +    public List<EventShortDto> getEvents(Long followerId, String type, Integer from, Integer size) {
Согласен. Убрал будущие и у создателей, и у участников. В принципе, можно даже потом ввести параметр запроса типа "ALL" и "FUTURE".

2022-09-30 15:14 UTC, sniskorodnova approved these changes
всё отлично!

2022-10-03 15:45 UTC, vbutrim commented on ewm-service/src/main/resources/schema.sql
> +    CONSTRAINT pk_user_follower PRIMARY KEY (user_id, follower_id),
а зачем нужен свой id? 
явно не вижу обращения к нему, кроме как для аппрува или отмены. (user_id, follower_id) должно быть достаточно

2022-10-03 15:46 UTC, vbutrim commented on ewm-service/src/main/java/ru/practicum/explorewithme/subscription/SubscriptionService.java
> +public interface SubscriptionService {
зачем нужен интерфейс с единственной имплементацией?

2022-10-03 15:46 UTC, vbutrim commented on ewm-service/src/main/java/ru/practicum/explorewithme/subscription/SubscriptionServiceImpl.java
> +public class SubscriptionServiceImpl implements SubscriptionService {
*Impl считается устаревшим устаревшим неймингом, старайся не использовать его, ведь он не несет никакой смысловой нагрузки для читающего

2022-10-03 15:47 UTC, vbutrim commented on ewm-service/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS user_follower
[nit] почему не subscription(s)?

2022-10-03 15:48 UTC, vbutrim commented on ewm-service/src/main/resources/schema.sql
> +    approved   BOOLEAN,
так подписку можно только апрувнуть. что будешь делать, если скажут добавить функционал decline-а (отклонения заявки человеком, которого хотят зафолоуить)?

2022-10-03 15:49 UTC, vbutrim commented on ewm-service/src/test/java/ru/practicum/explorewithme/subscription/SubscriptionServiceImplTest.java
> +    Event event = new Event(
[nit] private static final *?

2022-10-03 15:49 UTC, vbutrim commented on ewm-service/src/main/java/ru/practicum/explorewithme/subscription/SubscriptionController.java
> +    @PostMapping("/{userToSubId}")
[nit] followeeId

2022-10-03 15:50 UTC, vbutrim commented on ewm-service/src/main/java/ru/practicum/explorewithme/subscription/SubscriptionController.java
> +                                     @PathVariable Long userToSubId) {
лучше поместить параметр в тело сразу

2022-10-03 15:51 UTC, vbutrim commented on ewm-service/src/main/java/ru/practicum/explorewithme/subscription/SubscriptionController.java
> +                                                   @RequestParam(defaultValue = "0") Integer from,
здесь лучше указывать, к чему относится параметр во избежание неправильного чтения.
pageFrom и pageSize было бы оч кстати

2022-10-03 15:52 UTC, vbutrim commented on ewm-service/src/main/java/ru/practicum/explorewithme/subscription/SubscriptionService.java
> +    SubscriptionDto subscribe(Long followerId, Long userId);
сервис должен возвращать доменный объект и никак не dto

2022-10-03 16:04 UTC, vbutrim commented on ewm-service/src/main/java/ru/practicum/explorewithme/subscription/SubscriptionServiceImpl.java
> +    public List<EventShortDto> getEvents(Long followerId, String type, Integer from, Integer size) {
а чего параметр не enum?

2022-10-03 16:05 UTC, vbutrim commented on ewm-service/src/main/java/ru/practicum/explorewithme/subscription/SubscriptionServiceImpl.java
> +        result.forEach(e -> e.setViews(statsClient.getViews(e.getId())));
тут будет N запросов к statsClient-у, с учетом того, что соединение будет по http это довольно дорого. лучше сходить в statsClient по батчу и сразу забрать показы для пачки событий

2022-10-03 16:07 UTC, vbutrim commented on ewm-service/src/main/java/ru/practicum/explorewithme/subscription/Subscription.java
> +    public Subscription() {
[nit] @NoArgsConstructor?

2022-10-04 13:01 UTC, vbutrim commented on ewm-service/src/main/java/ru/practicum/explorewithme/subscription/SubscriptionService.java
> +    void approve(Long userId, Long subId);
почему в качестве аргументов используются обертки, а не примитивы?

2022-10-04 13:02 UTC, vbutrim requested changes
хорошая работа, Миш!
оставил несколько улучшалок.

спасибо за комментарии!

2022-10-04 15:18 UTC, MishaSmr commented on ewm-service/src/main/java/ru/practicum/explorewithme/subscription/SubscriptionService.java
> +public interface SubscriptionService {
Делал по аналогии с прошлыми учебными проектами, но, видимо, здесь это лишнее - исправил

2022-10-04 15:18 UTC, MishaSmr commented on ewm-service/src/main/java/ru/practicum/explorewithme/subscription/SubscriptionServiceImpl.java
> +public class SubscriptionServiceImpl implements SubscriptionService {
Оставил только SubscriptionService

2022-10-04 15:18 UTC, MishaSmr commented on ewm-service/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS user_follower
Согласен, заменил

2022-10-04 15:19 UTC, MishaSmr commented on ewm-service/src/main/resources/schema.sql
> +    approved   BOOLEAN,
Заменил на enum SubscriptionStatus

2022-10-04 15:19 UTC, MishaSmr commented on ewm-service/src/test/java/ru/practicum/explorewithme/subscription/SubscriptionServiceImplTest.java
> +    Event event = new Event(
Согласен, поправил

2022-10-04 15:38 UTC, MishaSmr commented on ewm-service/src/main/java/ru/practicum/explorewithme/subscription/SubscriptionController.java
> +    @PostMapping("/{userToSubId}")
Как же долго я искал подходящее слово! Спасибо. Но исходя из следующего замечания, здесь теперь ничего не нужно

2022-10-04 15:38 UTC, MishaSmr commented on ewm-service/src/main/java/ru/practicum/explorewithme/subscription/SubscriptionController.java
> +                                     @PathVariable Long userToSubId) {
Заменил на @RequestBody SubscriptionDto

2022-10-04 15:38 UTC, MishaSmr commented on ewm-service/src/main/java/ru/practicum/explorewithme/subscription/SubscriptionController.java
> +                                                   @RequestParam(defaultValue = "0") Integer from,
Исправил

2022-10-04 15:45 UTC, MishaSmr commented on ewm-service/src/main/java/ru/practicum/explorewithme/subscription/Subscription.java
> +    public Subscription() {
Добавил

2022-10-04 17:52 UTC, MishaSmr commented on ewm-service/src/main/java/ru/practicum/explorewithme/subscription/SubscriptionServiceImpl.java
> +        result.forEach(e -> e.setViews(statsClient.getViews(e.getId())));
Переделал. Создал отдельный метод в маппере для ивентов

2022-10-04 17:52 UTC, MishaSmr commented on ewm-service/src/main/java/ru/practicum/explorewithme/subscription/SubscriptionService.java
> +    SubscriptionDto subscribe(Long followerId, Long userId);
Исправил, буду знать.

2022-10-04 18:00 UTC, MishaSmr commented on ewm-service/src/main/java/ru/practicum/explorewithme/subscription/SubscriptionService.java
> +    void approve(Long userId, Long subId);
Исправил

2022-10-04 18:10 UTC, MishaSmr commented on ewm-service/src/main/java/ru/practicum/explorewithme/subscription/SubscriptionServiceImpl.java
> +    public List<EventShortDto> getEvents(Long followerId, String type, Integer from, Integer size) {
Создал enum для типов получаемых событий

2022-10-05 09:39 UTC, vbutrim commented on ewm-service/src/main/resources/schema.sql
> +    approved   BOOLEAN,
лучше ModerationStatus

во избежание добавления в SubscriptionStatus чего-то отличного от модерации

2022-10-05 09:40 UTC, vbutrim approved these changes
lgtm

2022-10-05 17:25 UTC, merged